version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - 27018:27017

  ganache:
    image: trufflesuite/ganache-cli:latest
    command: --deterministic -p 8545 -h 0.0.0.0
    ports:
      - 8545:8545

  server:
    build:
      context: ./server
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/voting
      JWT_SECRET: dev-secret
      BLOCKCHAIN_RPC: http://ganache:8545
      BLOCKCHAIN_MOCK: 'false'
      SKIP_DB: 'false'
    ports:
      - 5000:5000
    depends_on:
      - mongo
      - ganache

  client:
    build:
      context: ./client
    environment:
      VITE_API_BASE_URL: http://server:5000/api
    ports:
      - 5173:5173
    depends_on:
      - server

  seed:
    build:
      context: ./server
    command: npm run seed
    environment:
      MONGO_URI: mongodb://mongo:27017/voting
    depends_on:
      - mongo

volumes:
  mongo-data:

